[project]
name = "rules"
version = "0.1.0"
description = "A Python package for processing and applying rules."
authors = [
    { name = "Your Name", email = "youremail@example.com" },
]
requires-python = ">=3.6"
